(package "treesit-jump"
         "0.0.1"
         "Jump around code using treesit")

(website-url "https://github.com/dmille56/treesit-jump")
(keywords "treesit" "treesitter" "avy" "jump" "matching" "gptel")

(package-file "treesit-jump.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")
(source "melpa")  ; Add package archives

(depends-on "emacs" "29.1")
(depends-on "transient" "0.5.3")
(depends-on "avy" "0.4")
(depends-on "gptel" "0.8.5")
